# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - insurancechatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://insurancebot.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6bd5ac51e5424420a968c6c579530315 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_11424ce99f3340b88ffc01bc2160906a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: insurancebot.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bd5ac51e5424420a968c6c579530315 }}/insurance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'insurancechatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f21deb66fb324d79980e79a2ff7d9574 }}
        images: 'insurancebot.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bd5ac51e5424420a968c6c579530315 }}/insurance:${{ github.sha }}'